move_base:
  local_costmap:
    inflation_layer:
      cost_scaling_factor: 1
      inflation_radius: 0.25
    robot_radius: 0.15
  global_costmap:
    inflation_layer:
      cost_scaling_factor: 1
      inflation_radius: 0.15
    robot_radius: 0.15
